[options]
admin_passwd = rafi
addons_path = /usr/lib/python3/dist-packages/odoo/addons, /mnt/extra-addons
http_interface = 0.0.0.0

limit_memory_hard = 3221225472
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
max_cron_threads = 1
workers = 9
proxy_mode = True

log_handler = :INFO
log_level = info